version: '3.7'
services:
  clickhouse:
    image: clickhouse/clickhouse-server
    restart: always
    environment:
      - CLICKHOUSE_DB=logchain
      - CLICKHOUSE_USER=logchain
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_PASSWORD=L0gCh@in
    volumes:
      - ./clickhouse-data:/var/lib/clickhouse/
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '9000:9000'
      - '8123:8123'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - backend

  grafana:
    image: grafana/grafana:9.3.2
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/grafana
    networks:
      - backend

  logchain:
    image: adaptivelive/logchain:latest
    ports:
      - 9090:9090
    restart: unless-stopped
    networks:
      - backend
    environment:
      - DATABASE_TYPE=clickhouse 
      - DSN=clickhouse://logchain:L0gCh@in@clickhouse:9000/logchain?read_timeout=10s
      - PORT=9090
      - PROTECTED="false"
      - CERT_LOCATION=""
      - KEY_LOCATION=""
networks:
  backend: